apiVersion: v1
kind: Pod
metadata:
  name: todo-pod
  namespace: default
  labels:
    app: todo
spec:
  containers:
    - name: todo-next-app
      image: jamesnagar/todo-app-k8s-test:1
      ports: 
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: todo-svc
  namespace: default
spec:
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
